/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'classNumber' : string,
  'subject' : string,
  'createdAt' : bigint,
}
export interface PdfEntry {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'entryType' : string,
}
export interface Topic {
  'id' : bigint,
  'title' : string,
  'notesLabel1' : string,
  'notesLabel2' : string,
  'audioLabel1' : string,
  'audioLabel2' : string,
  'notesUrl1' : string,
  'notesUrl2' : string,
  'createdAt' : bigint,
  'chapterId' : bigint,
  'audioUrl1' : string,
  'audioUrl2' : string,
  'quizQuestions' : string,
  'flashcards' : string,
  'trueFalseQuestions' : string,
}
export interface TopicInput {
  'title' : string,
  'notesLabel1' : string,
  'notesLabel2' : string,
  'audioLabel1' : string,
  'audioLabel2' : string,
  'notesUrl1' : string,
  'notesUrl2' : string,
  'chapterId' : bigint,
  'audioUrl1' : string,
  'audioUrl2' : string,
  'quizQuestions' : string,
  'flashcards' : string,
  'trueFalseQuestions' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addChapter' : ActorMethod<[string, string, string], bigint>,
  'addPdfEntry' : ActorMethod<[string, string, string], bigint>,
  'addTopic' : ActorMethod<[TopicInput], bigint>,
  'deleteChapter' : ActorMethod<[bigint], boolean>,
  'deletePdfEntry' : ActorMethod<[bigint], boolean>,
  'deleteTopic' : ActorMethod<[bigint], boolean>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getAllPdfEntries' : ActorMethod<[], Array<PdfEntry>>,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getChapter' : ActorMethod<[bigint], [] | [Chapter]>,
  'getPdfEntry' : ActorMethod<[bigint], [] | [PdfEntry]>,
  'getTopic' : ActorMethod<[bigint], [] | [Topic]>,
  'getTopicsByChapter' : ActorMethod<[bigint], Array<Topic>>,
  'updateChapter' : ActorMethod<[bigint, string, string, string], boolean>,
  'updatePdfEntry' : ActorMethod<[bigint, string, string, string], boolean>,
  'updateTopic' : ActorMethod<[bigint, TopicInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];