/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChapterInput = IDL.Record({
  'title' : IDL.Text,
  'classNumber' : IDL.Text,
  'subject' : IDL.Text,
  'audioUrl' : IDL.Text,
  'notesUrl' : IDL.Text,
  'quizQuestions' : IDL.Text,
  'flashcards' : IDL.Text,
});
export const PdfEntryInput = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'entryType' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'classNumber' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'audioUrl' : IDL.Text,
  'notesUrl' : IDL.Text,
  'quizQuestions' : IDL.Text,
  'flashcards' : IDL.Text,
});
export const PdfEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'entryType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChapter' : IDL.Func([ChapterInput], [IDL.Nat], []),
  'addPdfEntry' : IDL.Func([PdfEntryInput], [IDL.Nat], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePdfEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getAllPdfEntries' : IDL.Func([], [IDL.Vec(PdfEntry)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'updateChapter' : IDL.Func([IDL.Nat, ChapterInput], [IDL.Bool], []),
  'updatePdfEntry' : IDL.Func([IDL.Nat, PdfEntryInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChapterInput = IDL.Record({
    'title' : IDL.Text,
    'classNumber' : IDL.Text,
    'subject' : IDL.Text,
    'audioUrl' : IDL.Text,
    'notesUrl' : IDL.Text,
    'quizQuestions' : IDL.Text,
    'flashcards' : IDL.Text,
  });
  const PdfEntryInput = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'entryType' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'classNumber' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'audioUrl' : IDL.Text,
    'notesUrl' : IDL.Text,
    'quizQuestions' : IDL.Text,
    'flashcards' : IDL.Text,
  });
  const PdfEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'entryType' : IDL.Text,
  });
  
  return IDL.Service({
    'addChapter' : IDL.Func([ChapterInput], [IDL.Nat], []),
    'addPdfEntry' : IDL.Func([PdfEntryInput], [IDL.Nat], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePdfEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getAllPdfEntries' : IDL.Func([], [IDL.Vec(PdfEntry)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'updateChapter' : IDL.Func([IDL.Nat, ChapterInput], [IDL.Bool], []),
    'updatePdfEntry' : IDL.Func([IDL.Nat, PdfEntryInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };